subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/typec/tcpc/inc
subdir-ccflags-y += -I$(srctree)/drivers/power/supply/mediatek/misc/
subdir-ccflags-y += -I$(srctree)/drivers/power/supply/mediatek/charger/

obj-$(CONFIG_CHARGER_LN8410)	+= ln8410.o
obj-$(CONFIG_CHARGER_LN8000)	+= ln8000.o
